# Generated by Django 5.2.4 on 2025-07-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_formularioadopcion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('adoptado', 'Adoptado'), ('en_proceso', 'En proceso de adopción')], default='disponible', max_length=50),
        ),
    ]
